version: '3.6'
services:
  '7.2': &base
    image: "circleci/php:7.2"
    ulimits:
      core: 99999999999
    working_dir: '/home/circleci/app'
    stdin_open: true
    tty: true
    volumes: [ '.:/home/circleci/app' ]
    tmpfs: [ '/home/circleci/app/tmp:uid=3434,gid=3434,exec' ]
    depends_on:
      - redis
      - ddagent
    environment:
      - REDIS_HOSTNAME=redis
      - DDAGENT_HOSTNAME=ddagent
    command: make -f DDMakefile install test_integration SUDO=sudo
  '5.6': { <<: *base, image: 'circleci/php:5.6' }
  '7.0': { <<: *base, image: 'circleci/php:7.0' }
  '7.1': { <<: *base, image: 'circleci/php:7.1' }
  redis:
    image: "circleci/redis:4.0-alpine"
  ddagent:
    image: datadog/agent:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "HEAD", "http://localhost:8126"]
      interval: 10s
      timeout: 2s
      retries: 2
    environment:
      - DD_APM_ENABLED=true
      - DD_BIND_HOST=0.0.0.0
      - DD_API_KEY=invalid_key_but_its_ok
    ports:
      - "8126:8126"
