version: 2.0

jobs:
  "php-5.6":
    docker:
      - image: circleci/php:5.6
    working_directory: ~/datadog
    steps:
      - checkout
      - run: composer install -n
      - run:
          name: Run lint
          command: composer lint
      - run:
          name: Run tests
          command: composer test

  "php-7.0":
    docker:
      - image: circleci/php:7.0
    working_directory: ~/datadog
    steps:
      - checkout
      - run: composer install
      - run:
          name: Run lint
          command: composer lint
      - run:
          name: Run tests
          command: composer test

workflows:
  version: 2
  build:
    jobs:
      - "php-5.6"
      - "php-7.0"
