version: 2.0

jobs:
  "php-5.6":
    docker:
      - image: circleci/php:5.6
      - image: datadog/docker-dd-agent
        environment:
        - DD_APM_ENABLED=true
        - DD_BIND_HOST=0.0.0.0
        - DD_API_KEY=invalid_key_but_this_is_fine
    working_directory: ~/datadog
    steps:
      - checkout
      - run:
          name: Install php-bcmath
          command: sudo docker-php-ext-install bcmath
      - run: composer install -n
      - run:
          name: Run lint
          command: composer lint
      - run:
          command: dockerize -wait tcp://127.0.0.1:8126 -timeout 1m
      - run:
          name: Run tests
          command: composer test

  "php-7.0":
    docker:
      - image: circleci/php:7.0
      - image: datadog/docker-dd-agent
        environment:
        - DD_APM_ENABLED=true
        - DD_BIND_HOST=0.0.0.0
        - DD_API_KEY=invalid_key_but_this_is_fine
    working_directory: ~/datadog
    steps:
      - checkout
      - run:
          name: Install php-bcmath
          command: sudo docker-php-ext-install bcmath
      - run: composer install
      - run:
          name: Run lint
          command: composer lint
      - run:
          command: dockerize -wait tcp://127.0.0.1:8126 -timeout 1m
      - run:
          name: Run tests
          command: composer test

  "php-7.1":
    docker:
      - image: circleci/php:7.1
      - image: datadog/docker-dd-agent
        environment:
        - DD_APM_ENABLED=true
        - DD_BIND_HOST=0.0.0.0
        - DD_API_KEY=invalid_key_but_this_is_fine
    working_directory: ~/datadog
    steps:
      - checkout
      - run:
          name: Install php-bcmath
          command: sudo docker-php-ext-install bcmath
      - run: composer install
      - run:
          name: Run lint
          command: composer lint
      - run:
          command: dockerize -wait tcp://127.0.0.1:8126 -timeout 1m
      - run:
          name: Run tests
          command: composer test

  "php-7.2":
    docker:
      - image: circleci/php:7.2
      - image: datadog/docker-dd-agent
        environment:
        - DD_APM_ENABLED=true
        - DD_BIND_HOST=0.0.0.0
        - DD_API_KEY=invalid_key_but_this_is_fine
    working_directory: ~/datadog
    steps:
      - checkout
      - run:
          name: Install php-bcmath
          command: sudo docker-php-ext-install bcmath
      - run: composer install
      - run:
          name: Run lint
          command: composer lint
      - run:
          command: dockerize -wait tcp://127.0.0.1:8126 -timeout 1m
      - run:
          name: Run tests
          command: composer test

workflows:
  version: 2
  build:
    jobs:
      - "php-5.6"
      - "php-7.0"
      - "php-7.1"
      - "php-7.2"
